modLoader="javafml"
loaderVersion="[47,)"
license="Academic Free License v3.0"

[[mods]]
modId="ice_and_fire_delight"
version="0.1.8"
displayName="Ice and Fire Delight"
updateJSONURL="https://raw.githubusercontent.com/Donne431/Ice_and_Fire_Delight-1.20.1/master/update.json"
displayURL="https://modrinth.com/mod/ice-and-fire-delight"
logoFile="logo.png"
credits="Don't forget join in my discord server!"
authors="Donne431"
description="Mod adds the integration of Ice and Fire with Farmer's Delight"

[[dependencies.ice_and_fire_delight]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"


[[dependencies.ice_and_fire_delight]]
    modId="farmersdelight"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.ice_and_fire_delight]]
    modId="patchouli"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.ice_and_fire_delight]]
    modId="iceandfire"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ice_and_fire_delight]]
    modId="just_enough_effect_descriptions"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.ice_and_fire_delight]]
    modId="patchouli"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.ice_and_fire_delight]]
    modId="allmods"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.ice_and_fire_delight]]
    modId="jei"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

